### ISSUE TITLE
Viewfinder zoomed in?

### ISSUE THREAD

**Issue by noudaniel** [PkmX/lcamera#143] opened 2015-02-23 05:21 UTC
The framing for taking photos seems to be cropped in/zoomed in.
However the resulting shots are normal.

**Comment by Srandista** [comment] 2015-02-23 20:53
I did some testing, and only in version 0.1 the preview on display is actually, what you get on photo. In all following version is preview on display different from result captured by camera. Tested on Nexus 5.

**Comment by PkmX** [comment] 2015-02-25 19:22
Closing as a duplicate of #126. I will look into this issue and please keep the discussion in one thread. Thanks.

**Closed by PkmX** 2015-02-25 19:22 UTC
