### ISSUE TITLE
Able to choose ISO < 100, but photos are taken with ISO 100

### ISSUE THREAD

**Issue by dattz** [PkmX/lcamera#128] opened 2015-01-18 10:55 UTC
Using nexus 5 5.0.1 with L Camera 0.3.
I am ablr to go upto ISO 40 with manual exposure, however, if I look at the photos details, they are taken with ISO 100 only. Limitation of nexus 5's camera is ISO 100 perhaps?

**Comment by PkmX** [comment] 2015-01-18 15:43
Yes. The ISO values between 40~100 are for Nexus 6.

The issue is already fixed in the `master` branch (yet to-be-released), so I'm closing this.

**Closed by PkmX** 2015-01-18 15:43 UTC
